### ISSUE TITLE
Open Source formatter for Sparta code

### ISSUE THREAD

**Issue by avinabadasgupta** [sparcians/map#58]
There is a high degree of code formatting inconsistency in Sparta codebase.
This task is about researching on several open source formatters and how to automate code formatting with git hooks (pre-commit) on every commit.

**Comment by dingiso** [comment]
What code format style does Sparta currently use?

For instance, Google and LLVM in clang-format.

Best regards,
Dingisoul

**Comment by klingaard** [comment]
Sparta was born and built before Google came around with their coding styles -- so we started with our own style guide.  I documented the rules here:

https://github.com/sparcians/map/tree/master/sparta#developing-on-sparta

There are overlaps with Google's recommendations, but since this is _always_ a contentious subject, I'd rather not force any changes.  

I'd _love_ to add hooks to ensure the standard, but I'm mostly relying on code reviews to be the mechanism to enforce it.

**Comment by klingaard** [comment]
Will probably look into clang-format.  Good work for map_v3

**Comment by timsnyder** [comment]
@klingaard how was this completed? Decided not to force changes and closed without doing? 

Just making sure I'm not missing something.

**Comment by klingaard** [comment]
This was closed possibly accidentally.  For map_v3, a clang-format would be good to install/support.  We can reopen once map_v3 gets going.
