### ISSUE TITLE
Queue, Buffer, and Pipeline should use in-place new

### ISSUE THREAD

**Issue by davidsifive** [sparcians/map#60]
I think there is a bug in sparta Queue, Buffer, and Pipeline.  These structures should use in-place new when allocating a new entry and call the destructor of an entry when it goes out of scope.  This would ensure that an 18 entry queue, for example, even if it allocates space for something like 64 entries in the implementation will only have 18 entries alive at any one time.  I tried to fix this in Queue (I believe it was Queue) but Knute said it was causing some issue.  Knute had to back out my changes from Sparta.  I never got back to this.  In my situation the 10 entry allocator for my 5 entry queue was aborting.

From Knute:
Yeah, I had to back this out — there were random seg faults in the Sparta testers using Queue. Destruction of popped, out or reach elements seems to be a better solution than the in-place new (possibly).

**Comment by klingaard** [comment]
Hey Avi, David tried to make a fix to this in the past, but I ran into seg faults with the examples.  Didn't have time to track it down.  Anyway, this is the issue explained out:

For performance, the resources will allocate up to twice as much memory (up to the next pow2) for the resource.  When items _inside_ the resource are popped or erased or invalidated, they remain "alive" until they are replaced by the user.  David wants them killed immediately.  He's seeing the issue with his allocators complaining that he's "run out of memory" when using an Allocator coupled with a Buffer or Queue.  As an example, if he has a buffer with 5 entries, technically he only needs an allocator for roughly 6 objects -- 5 "alive" in the buffer and 1 to replace on of those objects.  But since the Buffer doubles the size internally or speed, he needs 11.

**Comment by avinabadasgupta** [comment]
Will look into this.

**Comment by klingaard** [comment]
Thanks.  I think all we need is invalidation of the object on erase/pop/etc.  I don't think we need the in place new, but could be wrong.

**Comment by klingaard** [comment]
This was David's original commit: 0bd92035dd8ca44a364f55d6b6cf548274796b8b

**Comment by davidsifive** [comment]
The Queue allocates memory for next_pow_2(2*num_entries).  So, when I ask for 5 it allocates 16.  My allocator needs to be greater than 16 to not die.

Thanks for looking into this Avi.
David

**Comment by avinabadasgupta** [comment]
I think we should be allocating an array of unintialized elements in the Queue during its construction, in order to use placement new during push method. Currently, the queue constructor uses new operator to default-initialize the internal array of elements. We should use malloc to non-default-initialize this array, in order to use in-place new construction of elements in push method.

**Comment by avinabadasgupta** [comment]
@klingaard https://github.com/sparcians/map/tree/avi_issue_60

**Comment by avinabadasgupta** [comment]
@klingaard , okay so I looked at the issue. Core example runs now.
I had to increase the max memory blocks from 300 to 16910 for running 10K instructions.
The Allocator is shared by 4 different queues of ExampleInst and constant allocation and deallocation happens now since it is using placement new. Hence, the number of blocks needed to be increased.

**Comment by davidsifive** [comment]
Hi Avi,

I don’t understand.  How can there be 16910 ExampleInsts in-flight at the same time?

Thanks,
David

**Comment by avinabadasgupta** [comment]
> Hi Avi, I don’t understand. How can there be 16910 ExampleInsts in-flight at the same time? Thanks, David
> […](#)

Hi David,
I suspect there is something broken in the way these memory blocks are released.
I found that there are 16910 blocks allocated but only 14 are released back to the pool at the time the allocator is destructed.
I think many blocks are not properly returned back to the pool.
I am investigating this.

**Comment by avinabadasgupta** [comment]
Hi David,
I have fixed Queue to work with in-place new construction.
https://github.com/sparcians/map/pull/64
I will take a look at Buffer and Pipeline soon.
Thanks,
Avi

**Comment by avinabadasgupta** [comment]
Now that items are immediately killed when popped, do we need the Queue to hold twice as many elements?

**Comment by davidsifive** [comment]
I think so.  What if you have a full 4 entry queue and you want to push 4 and then pop 4 this cycle.  That happens all the time when modeling hardware.

**Comment by klingaard** [comment]
I think the design of the resources was to allow fast pushing/popping of elements using pointers.  It was easier if the pointer pointed to a pow2 number of objects -- you can mask the index for overflow.

**Comment by avinabadasgupta** [comment]
Queue done and merged.
Next, I will work on Array.

**Comment by avinabadasgupta** [comment]
Array done and merged.
I'll take on Pipe and Pipeline next.

**Comment by klingaard** [comment]
Awesome.  I'm removing the `sparta::Resource` inheritance from them right now.

**Comment by klingaard** [comment]
Going to close this as completed.  Will revisit Pipe and Pipeline if needed.
